import type { Metadata } from "next";
import { IBM_Plex_Mono, Comfortaa } from "next/font/google";
import { Toaster } from "@/components/ui/toaster";
import "./globals.css";
import NextAuthProvider from "@/providers/NextAuthProvider";
import ProgressBarProvider from "@/providers/ProgressBarProvider";

const ibmMono = IBM_Plex_Mono({
  variable: "--font-mono",
  subsets: ["cyrillic"],
  weight: "500",
});

const comfortaa = Comfortaa({
  variable: "--font-sans",
  subsets: ["cyrillic"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Saweria Clone",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${ibmMono.variable} ${comfortaa.variable} antialiased`}>
        <ProgressBarProvider>
          <NextAuthProvider>
            {children}
            <Toaster />
          </NextAuthProvider>
        </ProgressBarProvider>
      </body>
    </html>
  );
}
